### ISSUE TITLE
keychords to invoke commands

### ISSUE THREAD

**Issue by zenny** [herbstluftwm/herbstluftwm#1137] opened 2021-01-14 11:15 UTC
HI,

 is there a possibility of assigning keychords to accomplish specific tasks similar to discussion here (https://www.reddit.com/r/i3wm/comments/kvqcf4/is_it_possible_to_bind_mod_two_letters/) or nifty implementation in i3 (https://github.com/EllaTheCat/dopamine-2020)?

Btw, @The-Compiler pointed in #1135 to:

> There's some discussion about this in #751 as well as a keychain.sh script.

Any more inputs? Cheers, and stay safe.

**Comment by The-Compiler** [comment] 2021-01-14 14:05
What about this isn't covered by my answer in #1135 and #751 already?

**Comment by zenny** [comment] 2021-01-16 09:23
> What about this isn't covered by my answer in #1135 and #751 already?

Thanks @The-Compiler I just tried to separate the issues. I am yet to explore the links you provided, and get back as soon as I get the desired results.

**Comment by t-wissmann** [comment] 2022-01-26 15:52
Right, this seems to be a duplicate of #1135 and #751. Feel free to join the discussion there.

**Closed by t-wissmann** 2022-01-26 15:52 UTC
