### ISSUE TITLE
[Question] how to fix background trailis

### ISSUE THREAD

**Issue by adamgajzlerowicz** [herbstluftwm/herbstluftwm#402] opened 2019-04-12 07:44 UTC
If I have a floating window, whatever is "behind it" never refreshes. So if I get a notification that will come on that area, or I refresh size of that floated window parts of that box stay in the "background" behind it. Can I fix it somehow please?

Thanks!

**Comment by t-wissmann** [comment] 2019-04-13 15:06
Can you reproduce it or can you send a screenshot of it? I have the impression that either I don't understand it, or that it's a hlwm bug.

**Comment by adamgajzlerowicz** [comment] 2019-04-13 19:56
![image](https://user-images.githubusercontent.com/675615/56084690-f8631a00-5e36-11e9-92dd-23650f7c9ed4.png)

**Comment by adamgajzlerowicz** [comment] 2019-04-13 19:57
At some point notification was there. Now it is still visible, because android emulator a floating window. Is this making sense?
Thanks!

**Comment by Azulinho** [comment] 2019-06-07 10:20
AHA!
this is the problem I am having, I was assuming it was a problem with my app (slack in my case), as it hangs quite frequently, but I coudn't figure out what it was.
I read this issue here a few days ago, and today when my slack 'hanged' most of my desktop, I noticed it was because I had another window active and a slack notification (x2) come up.
I can only gain access to swap my focus by killing that window with active notifications.

my workaround just for this one is to disable all pop up notifications., but I expect to see a few more of these ones

**Comment by t-wissmann** [comment] 2019-10-03 07:42
As for #543, I'm wonderung whether this bug is fixed in the winterbreeze branch, where the issue with `telegram-desktop -startintray` is fixed (the fixing PR was #551, commit cf7a170c41d66a935bc09aa8f5f80859894076fc).

**Closed** 2024-07-28 08:11 UTC
