### ISSUE TITLE
No Qt showEvent triggered when switching workspaces

### ISSUE THREAD

**Issue by The-Compiler** [herbstluftwm/herbstluftwm#81] opened 2016-08-10 19:31 UTC
With this PyQt script:

``` python
from PyQt5.QtWidgets import QApplication, QWidget

class Widget(QWidget):
    def showEvent(self, e):
        print("showEvent")
        super().showEvent(e)

app = QApplication([])
w = Widget()
w.show()
app.exec_()
```

I'd expect to see "showEvent" every time I switch to the workspace that widget is on. However, I only see one initial "showEvent" when the widget is originally mapped.

On XMonad it seems to work correctly according to @haasn

**Comment by The-Compiler** [comment] 2016-08-11 15:16
Though according to https://github.com/The-Compiler/qutebrowser/pull/1833#issuecomment-239192315 the behavior is the same (no subsequent showEvents) in i3.

**Comment by ypnos** [comment] 2016-08-30 12:29
I just realized that the bug I am observing with Terminology might be related to this.
When I switch to a tag with Terminology windows, often these are not drawn (just black, as my background) until I focus them. Probably they also don't receive a show event and some Enlightment logic prevents them from drawing correctly without it. As a damage event surely should be sent.

**Comment by t-wissmann** [comment] 2021-03-09 12:50
Sorry that I didn't react to this. It wasn't on my radar at all. In the current hlwm, this seems to be fixed. Do you still observe any issue that might be related to this?

**Comment by ypnos** [comment] 2021-03-28 12:56
Closing as the provided test script works as intended and I also do not observe the faulty behavior with Terminology anymore.

**Closed by ypnos** 2021-03-28 12:56 UTC
