### ISSUE TITLE
pop-ups as floating windows

### ISSUE THREAD

**Issue by rohshall** [herbstluftwm/herbstluftwm#91] opened 2017-01-03 15:29 UTC
Popups by applications should be automatically floated, and not treated as normal windows with which the originating application shares screen space.

**Comment by The-Compiler** [comment] 2017-01-03 16:14
This looks like a duplicate of #14

**Comment by bklaase** [comment] 2017-01-22 13:52
What works really well, is having a frame in which you expect the application to create dialogues, be in the 'max' layout. The popup will now be pseudotiled in front of the parent application, like in the screenshot:

![screenshot](http://i.imgur.com/TG53J0F.png), due to these two 'default' rules:

    hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
    hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on

**Comment by ypnos** [comment] 2017-01-22 16:55
In all fairness, that only works as suggested if your frame is in `max` layout.

**Comment by bklaase** [comment] 2017-01-22 21:28
that's what I said ;)

**Comment by razzintown** [comment] 2017-09-06 20:21
Is it feasible to let these two rules work in all layouts? That would probably improve popup behavior for a lot of cases.

**Comment by ThomasJunk** [comment] 2017-10-22 08:54
I would prefer a behaviour similar to i3 et. al.
That is the only showstopper for me.

Currently I work with:

```hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on```

```hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off focus=off```

That does somehow the trick for me, but is not really cool.

**Comment by t-wissmann** [comment] 2020-04-05 13:18
Dear @rohshall, @bklaase, @ypnos, @gayprogrammer, @ThomasJunk, and others,

I've implemented single window floating in the current git version of herbstluftwm (and winterbreeze was merged two  weeks ago). I'm sorry for letting you all wait for this feature so long. If I recall correctly, this was one of the earliest feature requests (in 2011).

I'd be happy if you try the current git version of herbstluftwm and try it! The command
```
hc attr clients.focus.floating toggle
```
toggles the floating state of the focused window. I've added this keybinding to my (and the default) autostart
```
hc keybind $Mod-Shift-f attr clients.focus.floating toggle
```
Maybe you have another suggestion what the default keybinding should be (i3 uses `$Mod-Shift-space` iirc). Popup dialogs are floated automatically, and to float further windows, one can use `floating=on` in rules.

If you notice any strange behaviour or even crashes, please open an issue here on github, or report it by mail or on the irc.

Thank you for using herbstluftwm!

**Closed by t-wissmann** 2020-04-05 13:18 UTC

**Comment by bklaase** [comment] 2020-04-05 14:29
Great! thanks for letting us know !
