### ISSUE TITLE
Feature request: floating dialog windows

### ISSUE THREAD

**Issue by pepib** [herbstluftwm/herbstluftwm#39] opened 2015-03-24 17:06 UTC
As by title. Is possible to have in the next release the dialog windows float?

**Comment by The-Compiler** [comment] 2015-03-24 17:30
Closing this as a duplicate of #14.

It's definitely a much requested feature - it's just that the main developer (@t-wissmann) doesn't use it, and I'm currently busy with another project - so someone would have to step up and implement it.

**Closed by The-Compiler** 2015-03-24 17:30 UTC
Labels: duplicate

**Comment by t-wissmann** [comment] 2020-04-05 13:22
Dear @p3p1, 
I've just implemented single window floating in the current git version, and popup dialogs are floated automatically. Sorry for letting you wait so long!

See also this comment how to use it: https://github.com/herbstluftwm/herbstluftwm/issues/14#issuecomment-609414813

Thanky you for using herbstluftwm!
